version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/test?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: 3025
    ports:
      - 8080:8080

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - 3000:3000
#    depends_on:
#      - backend
