version: '3'
services:
  spring-app:
    image: your-spring-app-image
    ports:
      - "8080:8080"
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge