spring:
  application:
    name: vocatest
  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/vocatest
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect